# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a645618fcf0ae64474208c3fc4efe2ba5814a9134b3e43b389d466f0653323692cdbb40b371d600a057672add3354c90f4d8a271030d36945160b6893e384a97

test:
  secret_key_base: feb85dcafec2d66bbdabb1732380fb8d1ae4ec7040abf6ea98649cf8c1292ab33b6e5be8706604353e8013ad1be85651e205db77ecb8f76943d689166b044d09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
